services:
  server:
    build:
      target: development
    develop:
      watch:
        - action: rebuild
          path: ./Server/ReasnAPI/ReasnAPI
        
  postgres:
    expose:
      - 5432
    volumes:
      - ./Database/init-dev-data.sql:/docker-entrypoint-initdb.d/03-init-dev-data.sql
  