version: "3.8"

services:
  postgres:
    image: postgres:16
    networks:
      - reasn-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Database/init-db-values.sql:/docker-entrypoint-initdb.d/init-db-values.sql
      - ./Database/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    env_file:
      - .env
      - .env.sample

  pgadmin:
    image: dpage/pgadmin4:8.0
    networks:
      - reasn-network
    ports:
      - "${PGADMIN_LISTEN_PORT:-5050}:${PGADMIN_LISTEN_PORT:-5050}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    depends_on:
      - postgres

networks:
  reasn-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:


