name: 🐛 Bug Report
description: Report a reproducable bug.
title: "<title>"
labels: ["type: bug"]
body:
  - type: textarea
    attributes:
      label: What is the current behaviour?
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the expected behaviour?
      description: A concise description of what you expected to happen.

  - type: textarea
    attributes:
      label: How to reproduce it?
      description: Steps to reproduce this behaviour.

