#!/bin/bash


set -e


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

	CREATE USER "$POSTGRES_ADMIN_USER" WITH LOGIN PASSWORD '$POSTGRES_ADMIN_PASSWORD';
	GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_ADMIN_USER;
	GRANT USAGE ON SCHEMA public TO $POSTGRES_ADMIN_USER;
	GRANT CREATE, INSERT, SELECT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $POSTGRES_ADMIN_USER;
	REVOKE ALL ON event_parameters, event_tags, user_interests  FROM $POSTGRES_ADMIN_USER;


	CREATE USER "$POSTGRES_CLIENT_USER" WITH LOGIN PASSWORD '$POSTGRES_CLIENT_PASSWORD';
        GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_CLIENT_USER;
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO $POSTGRES_CLIENT_USER;
        GRANT SELECT, UPDATE, INSERT, DELETE ON comments, events, addresses, interests TO $POSTGRES_CLIENT_USER;
        GRANT SELECT, UPDATE, INSERT ("name", surname, username, "password", email, phone) ON "users" TO $POSTGRES_CLIENT_USER;

EOSQL




